steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/escrow-service-bot:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/escrow-service-bot:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'escrow-service-bot'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/escrow-service-bot:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--timeout=600s'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--cpu-boost'
      - '--min-instances=1'
      - '--max-instances=1'
      - '--concurrency=80'

# Store images in Artifact Registry  
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/escrow-service-bot:$COMMIT_SHA'

# Use a longer timeout for the build process
timeout: '1200s'

# Required IAM permissions for Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY