version: '3.8'

services:
  queen:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://26d4-2c0f-2a80-70-a410-00-d7a.ngrok-free.app"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s