version: '3.8'

services:
  escrow-bot:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TOKEN=${TOKEN}
      - WEBHOOK_MODE=${WEBHOOK_MODE}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ADMIN_ID=${ADMIN_ID}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - BTCPAY_URL=${BTCPAY_URL}
      - BTCPAY_STORE_ID=${BTCPAY_STORE_ID}
      - BTCPAY_API_KEY=${BTCPAY_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./bot.log:/bot.log