"""re-create tables

Revision ID: 823a79edff09
Revises: 481372a5a95d
Create Date: 2023-11-12 00:59:07.560224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823a79edff09'
down_revision: Union[str, None] = '481372a5a95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('admin_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agent')
    op.drop_table('affiliates')
    op.add_column('disputes', sa.Column('user_id', sa.String(length=20), nullable=True))
    op.add_column('disputes', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('disputes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('disputes', 'trade_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('disputes', 'complaint',
               existing_type=sa.VARCHAR(length=162),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint('disputes_id_key', 'disputes', type_='unique')
    op.drop_constraint('disputes_trade_id_fkey', 'disputes', type_='foreignkey')
    op.create_foreign_key(None, 'disputes', 'trades', ['trade_id'], ['id'])
    op.create_foreign_key(None, 'disputes', 'users', ['user_id'], ['id'])
    op.drop_column('disputes', 'created_on')
    op.drop_column('disputes', 'user')
    op.add_column('trades', sa.Column('seller_id', sa.String(length=20), nullable=True))
    op.add_column('trades', sa.Column('buyer_id', sa.String(length=20), nullable=True))
    op.add_column('trades', sa.Column('invoice_id', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('trades', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('trades', sa.Column('chat_id', sa.String(length=20), nullable=True))
    op.alter_column('trades', 'id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('trades', 'currency',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('trades', 'created_at',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('trades', 'updated_at',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'trades', 'users', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'chats', ['chat_id'], ['id'])
    op.drop_column('trades', 'is_open')
    op.drop_column('trades', 'agent_id')
    op.drop_column('trades', 'address')
    op.drop_column('trades', 'invoice')
    op.drop_column('trades', 'wallet')
    op.drop_column('trades', 'coin')
    op.drop_column('trades', 'buyer')
    op.drop_column('trades', 'payment_status')
    op.drop_column('trades', 'seller')
    op.add_column('users', sa.Column('name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')
    op.add_column('trades', sa.Column('seller', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('payment_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('buyer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('coin', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('wallet', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('invoice', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('agent_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.alter_column('trades', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('trades', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('trades', 'currency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('trades', 'id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('trades', 'chat_id')
    op.drop_column('trades', 'is_paid')
    op.drop_column('trades', 'is_active')
    op.drop_column('trades', 'invoice_id')
    op.drop_column('trades', 'buyer_id')
    op.drop_column('trades', 'seller_id')
    op.add_column('disputes', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('disputes', sa.Column('created_on', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key('disputes_trade_id_fkey', 'disputes', 'trades', ['trade_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('disputes_id_key', 'disputes', ['id'])
    op.alter_column('disputes', 'complaint',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=162),
               existing_nullable=True)
    op.alter_column('disputes', 'trade_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.drop_column('disputes', 'created_at')
    op.drop_column('disputes', 'is_resolved')
    op.drop_column('disputes', 'user_id')
    op.create_table('affiliates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name='affiliates_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='affiliates_pkey')
    )
    op.create_table('agent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mnemonic', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('xpub', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('btc_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('eth_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('store', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agent_pkey')
    )
    op.drop_table('chats')
    # ### end Alembic commands ###
