"""add terms

Revision ID: e0375da955c8
Revises: db8ac6fc2df0
Create Date: 2023-11-21 00:35:55.214020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0375da955c8'
down_revision: Union[str, None] = 'db8ac6fc2df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('terms', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'terms')
    # ### end Alembic commands ###
